"""Local, dependency-free UI served by :mod:`strangeloop.monitor`."""

from __future__ import annotations


def dashboard_html() -> str:
    """Return a plain-language local dashboard with opt-in technical details.

    All dynamic values are assigned through ``textContent``; the page never
    interprets ledger data as HTML and makes no network request except to its
    own local JSON endpoints.
    """
    return """<!doctype html><html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Strangeloop 工作看板</title><style>
:root{color-scheme:dark;--bg:#101419;--card:#1b232c;--ink:#edf3f7;--muted:#a9b7c2;--line:#344451;--accent:#75d6a4;--warn:#ffca78;--bad:#ff9b9b}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px system-ui,-apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;line-height:1.55}main{max-width:1120px;margin:auto;padding:22px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.wide{grid-column:1/-1}.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px}h1{margin:0 0 3px;font-size:26px}h2{font-size:16px;margin:0 0 8px;color:var(--accent)}p{margin:7px 0}.muted{color:var(--muted);font-size:14px}.status{float:right;color:var(--accent)}.big{font-size:20px;font-weight:700}.ok{color:var(--accent)}.warn{color:var(--warn)}.bad{color:var(--bad)}ul{padding-left:20px;margin:6px 0;max-height:300px;overflow:auto}.event{border-top:1px solid var(--line);padding:7px 0}textarea{width:100%;min-height:88px;background:#111820;color:var(--ink);border:1px solid var(--line);border-radius:8px;padding:10px;font:inherit}button{margin-top:8px;padding:8px 14px;border:0;border-radius:8px;background:var(--accent);color:#102018;font-weight:700;cursor:pointer}button:disabled{opacity:.5;cursor:wait}.chat{white-space:pre-wrap;border-top:1px solid var(--line);padding:9px 0}details{margin-top:18px}summary{cursor:pointer;color:var(--muted);padding:10px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}code{font-family:ui-monospace,monospace;overflow-wrap:anywhere}@media(max-width:500px){main{padding:12px}h1{font-size:21px}}</style></head>
<body><main><h1>Strangeloop 工作看板 <span id="health" class="status">连接中</span></h1>
<p class="muted">这里显示的是能被账本回查的决策过程：目标、条件、选择、行动和结果。不会把一段事后编写的解释冒充成原始思维。</p>
<section class="grid">
<article class="card wide"><h2>现在情况</h2><p class="big" id="plainStatus">读取中…</p><p id="plainWhy" class="muted"></p></article>
<article class="card wide"><h2>本轮要验证什么</h2><p id="missionNow">读取中…</p></article>
<article class="card wide"><h2>这一步为什么能做</h2><p id="decisionBasis">读取中…</p></article>
<article class="card"><h2>它正在做什么</h2><p id="workNow">读取中…</p></article>
<article class="card"><h2>研究进展</h2><p id="researchNow">读取中…</p></article>
<article class="card"><h2>实验与学习</h2><p id="experimentNow">读取中…</p></article>
<article class="card"><h2>资源与自动维护</h2><p id="resourcesNow">读取中…</p></article>
<article class="card wide"><h2>直接和它对话</h2><p class="muted">你的消息会作为明确的用户输入交给主线程处理；回复只显示正常对话内容，不附带隐藏推理或工具权限。</p><textarea id="chatInput" maxlength="2000" placeholder="例如：你现在正在验证什么？请用通俗语言回答。"></textarea><button id="chatSend" type="button">发送给 Strangeloop</button><p id="chatNotice" class="muted"></p><ul id="chatHistory"></ul></article>
<article class="card wide"><h2>逐步决策记录</h2><p class="muted">每一行对应一个已写入账本的步骤；“未记录”不会被补写成解释。</p><ul id="plainTimeline"></ul></article>
</section>
<details><summary>查看技术详情（用于排障）</summary><section class="grid">
<article class="card"><h2>Public goal and turn</h2><p id="goal">Loading…</p><p class="muted" id="turn"></p></article>
<article class="card"><h2>DMN loop and budgets</h2><pre id="loop">Loading…</pre></article>
<article class="card"><h2>Unattended research</h2><pre id="unattended">Loading…</pre></article>
<article class="card"><h2>Expedition / frontier learning</h2><pre id="expedition">Loading…</pre></article>
<article class="card"><h2>K3 quota / conservation</h2><pre id="quota">Loading…</pre></article>
<article class="card"><h2>Quota sleep / wake</h2><pre id="sleep">Loading…</pre><ul id="archives"></ul></article>
<article class="card"><h2>K3 model invocation</h2><ul id="models"></ul></article>
<article class="card"><h2>Tool authorization stages</h2><ul id="tools"></ul></article>
<article class="card"><h2>Seeds and self-model claims</h2><ul id="claims"></ul></article>
<article class="card"><h2>Seed auto-update</h2><pre id="standingSeedPolicy">Loading…</pre></article>
<article class="card"><h2>自证／证自证镜映</h2><ul id="mirrors"></ul></article>
<article class="card"><h2>TD / RPE and stops</h2><ul id="learning"></ul></article>
<article class="card wide"><h2>Public event timeline</h2><ul id="events"></ul></article></section></details>
</main><script>
const byId=id=>document.getElementById(id), put=(id,items)=>{const el=byId(id);el.replaceChildren();(items||[]).forEach(item=>{const li=document.createElement('li');li.textContent=typeof item==='string'?item:JSON.stringify(item);el.appendChild(li)})};
function line(e){const p=e.payload||{},summary=p.public_summary||p.summary||p.outcome||'';return '#'+e.sequence+' '+e.kind+(summary?' — '+summary:'')}
function mirrorLine(e){const p=e.payload||{},codes=Array.isArray(p.check_codes)?p.check_codes.join(', '):'—';return '#'+e.sequence+' '+(p.mirror_id||'—')+' | self='+ (p.self_status||'—')+' @ '+(p.self_confidence??'—')+' | meta='+(p.meta_status||'—')+' cap='+(p.meta_confidence_cap??'—')+' | '+(p.disposition||'—')+' | checks: '+codes}
function archiveLine(a){return (a.archive_id||'—')+' | epoch '+(a.epoch_id||'—')+' | digest '+(a.archive_digest||'—')+' | events '+(a.event_count??'—')+' | head '+(a.chain_head_hash||'—')+' | manifest '+(a.schema_version??'—')+'/'+(a.chain_head_sequence??'—')+' | quota '+(a.quota_remaining??'—')+'/'+(a.quota_total??'—')+' | window '+(a.quota_window_kind||'—')}
function quotaLine(q){const balance=(Number.isInteger(q.remaining)&&Number.isInteger(q.total))?q.remaining+'/'+q.total+' '+(q.primary_unit||'units'):'unknown';const primaryWindow=(q.primary_window_kind==='weekly'||q.primary_window_kind==='rolling_5h')?q.primary_window_kind:'unknown';return 'K3 Plan remaining: '+balance+'\\nprimary window: '+primaryWindow+'\\nreset: '+(q.reset_at||'unknown')+'\\nobserved: '+(q.observed_at||'unknown')+'\\nauthority/freshness: '+(q.authority||'unknown')+' / '+(q.freshness||'unknown')+'\\nallow call: '+(q.allow_call===true?'yes':'no')+'\\nreason: '+(q.reason||'unknown')+'\\nlocal observed calls/tokens (not plan): '+(q.local_observed_calls??'—')+' / '+(q.local_observed_tokens??'—')}
function count(v){return Number.isInteger(v)&&v>=0?v:0}
function plainState(e,q){if(e.state==='active')return ['正在工作','正在执行第 '+count(e.slice)+' 个研究片段。'];if(e.state==='waiting_quota_retry')return ['正在等待配额刷新','在拿到新的服务端配额读数前，不会运行工具。'];if(e.state==='sleeping')return ['已进入资源等待','只有满足正式归档条件时才会在配额恢复后继续。'];if(e.state==='stopped')return ['已停止','原因：'+(e.stop_reason||'需要新的授权或外部恢复。')];if(e.state==='completed')return ['本轮已完成','当前授权窗口已结束。'];return ['尚未开始','等待一轮已授权研究。']}
function plainWork(e,u){if(e.state!=='active')return '当前没有在执行研究工具。';const calls=count(u.calls),max=count(u.max_calls);const tool=u.last_tool?'最近正在使用 '+u.last_tool+'。':'正在选择下一项只读研究动作。';return tool+' 本片段已用 '+calls+'/'+max+' 次受限调用。'}
function plainResearch(e){const sources=count(e.domain_count),findings=count(e.useful_findings),empty=count(e.empty_searches),failed=count(e.planner_failures);let text='已直接读取 '+sources+' 个公开来源，记录 '+findings+' 个可用外部发现。';if(empty)text+=' '+empty+' 次搜索没有安全结果。';if(failed)text+=' '+failed+' 次规划未完成，均未执行工具。';return text}
function plainExperiment(e){const x=e.experiment||{},done=count(x.completed_count),dupes=count(e.duplicate_experiment_result_count),reward=count(e.reward_count),td=count(e.td_update_count);let text='已完成 '+done+' 个固定离线实验；累计 '+reward+' 次合格奖励与 '+td+' 次 TD 更新。';if(x.last_kind){text+=' 最近是 '+x.last_kind+'，结果为 '+(x.last_status||'未知')+'。';if(x.reproducible&&x.control_valid&&x.reward_qualified===false)text+=' 这是可复现的重复结果：完成任务，但不重复奖励。'}if(dupes)text+=' 已抑制 '+dupes+' 个重复结果。';return text}
function plainResources(q,p,g){const quota=(Number.isInteger(q.remaining)&&Number.isInteger(q.total))?q.remaining+'/'+q.total:'未知';const allowed=q.allow_call===true?'当前可继续调用。':'当前不调用，等待新配额读数。';const seeds=count(p.active_count);let graph='图谱已同步。';if(g.status==='available'&&count(g.ledger_lag_events)>0)graph='图谱会在当前片段结束后补齐 '+count(g.ledger_lag_events)+' 条新记录。';return '服务端配额 '+quota+'（'+(q.primary_window_kind||'未知窗口')+'），'+allowed+' 自动种子：'+seeds+' 条活动。'+graph}
function rankingReason(reason){const names={fairness_persona_due:'为避免某个研究角色长期被跳过，轮换优先。',ranker_active_recommendation:'在已获准的候选中，学习排序选中了当前任务。',experiment_cadence_due:'已到固定离线实验的计划周期。',experiment_cadence_due_ranker:'已到实验周期，并在合格实验中完成排序。',experiment_cadence_due_shadow:'影子模式记录了实验周期，但不把学习结果用于选择。'};return names[reason]||'当前没有可公开的排序原因记录。'}
function decisionBasis(e,q,p){const quota=q.allow_call===true?'服务端配额新鲜且允许调用':'当前配额条件不允许调用';const seeds=count(p.active_count)?'已载入 '+count(p.active_count)+' 条活动种子的核验导向提示。':'没有活动种子参与排序。';const persona=e.persona?'本片段研究角色：'+e.persona+'。':'研究角色尚未记录。';return quota+' 只读工具权限仍由主机控制；'+seeds+' '+persona+' '+rankingReason(e.last_ranking_reason)}
function eventTime(e){return e.created_at?e.created_at.replace('T',' ').replace(/\+00:00$/,' UTC'):''}
function decisionEvent(e){const p=e.payload||{},tool=p.tool_name||'',prefix='#'+e.sequence+(eventTime(e)?' · '+eventTime(e):'')+'：';if(e.kind==='expedition_seed_context')return prefix+'刷新了当前有效的种子提示；它只影响已合格候选的软排序。';if(e.kind==='frontier_ranking_decision')return prefix+'调度器在授权、配额和角色轮换均通过后，确定了下一项研究任务。';if(e.kind==='frontier_vector_value_estimate')return prefix+'为这次选择保存了学习估计，供后续可复核的 TD 更新使用。';if(e.kind==='capability_granted')return prefix+'主机仅授予 '+(p.capability||tool||'受限工具')+' 的只读权限；不包含写入权限。';if(e.kind==='model_invocation'){if(p.outcome==='started')return prefix+'开始请求一个受限的只读行动计划。';if(p.outcome==='failed')return prefix+'本次规划不可用；因此没有执行任何工具。';return prefix+'规划阶段结束；主机仍会逐项检查权限和预算。'}if(e.kind==='tool_call_proposed')return prefix+'提议使用 '+(tool||'受限工具')+'，等待主机按只读规则执行。';if(e.kind==='tool_execution_started')return prefix+'开始执行已允许的 '+(tool||'受限工具')+'。';if(e.kind==='tool_result'){const result=p.summary||p.public_summary||'';if(p.outcome==='failed')return prefix+(tool||'工具')+' 失败或被拒绝；没有写入操作。';return prefix+(tool||'工具')+' 已完成。'+(result?' 结果：'+result:'')}if(e.kind==='experiment_plan_locked')return prefix+'锁定一项预注册的固定离线实验。';if(e.kind==='experiment_execution_started')return prefix+'开始运行固定离线实验。';if(e.kind==='experiment_result')return prefix+'独立验证器返回实验结果；只有合格的新结果才可能进入奖励。';return null}
function chatLine(item){const status=item.status==='queued'?'等待主线程处理':item.status==='processing'?'正在生成普通回复':item.status==='failed'?'未完成':'已回复';let text=status+'\\n你：'+(item.message||'');if(item.response)text+='\\nStrangeloop：'+item.response;if(Array.isArray(item.notices)&&item.notices.length)text+='\\n提示：'+item.notices.join('；');return text}
async function refreshChat(){try{const chat=await fetch('/api/chat').then(r=>r.json());put('chatHistory',(chat.messages||[]).slice().reverse().map(chatLine))}catch(e){byId('chatNotice').textContent='对话暂不可用。'}}
async function sendChat(){const input=byId('chatInput'),button=byId('chatSend'),message=input.value.trim();if(!message)return;button.disabled=true;byId('chatNotice').textContent='已提交，等待主线程处理。';try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});const receipt=await response.json();if(!response.ok)throw new Error(receipt.error||'refused');input.value='';byId('chatNotice').textContent='消息已进入本机对话队列。';await refreshChat()}catch(e){byId('chatNotice').textContent='消息未送达；没有执行任何动作。'}finally{button.disabled=false}}
async function refresh(){try{const [state,events,health]=await Promise.all([fetch('/api/state').then(r=>r.json()),fetch('/api/events?after_sequence=0').then(r=>r.json()),fetch('/api/health').then(r=>r.json())]);const e=state.expedition||{},q=state.quota||{},u=state.unattended||{},p=state.standing_seed_policy||{},g=state.memory_graph||{};const status=plainState(e,q);byId('health').textContent=health.status==='ok'?'本地监控正常':'连接异常';byId('plainStatus').textContent=status[0];byId('plainWhy').textContent=status[1];byId('missionNow').textContent=e.public_goal||'当前运行没有可公开的研究目标记录。';byId('decisionBasis').textContent=decisionBasis(e,q,p);byId('workNow').textContent=plainWork(e,u);byId('researchNow').textContent=plainResearch(e);byId('experimentNow').textContent=plainExperiment(e);byId('resourcesNow').textContent=plainResources(q,p,g);const recent=(events.events||[]).slice(-32).reverse().map(decisionEvent).filter(Boolean);put('plainTimeline',recent.length?recent:['暂时没有新的可展示工作步骤。']);byId('goal').textContent=e.public_goal||state.current_goal||'No public goal recorded.';byId('turn').textContent=state.current_turn?'Turn: '+state.current_turn:'No public turn recorded.';byId('loop').textContent=JSON.stringify(state.dmn_loop||{},null,2);byId('unattended').textContent=JSON.stringify(u,null,2);byId('expedition').textContent=JSON.stringify(e,null,2);byId('quota').textContent=quotaLine(q);const sleep=state.sleep_wake||{};byId('sleep').textContent=JSON.stringify(sleep.coordinator||{},null,2);byId('standingSeedPolicy').textContent=JSON.stringify(p,null,2);put('archives',(sleep.archives||[]).map(archiveLine));put('models',(state.model_invocations||[]).map(line));put('tools',(state.tool_stages||[]).map(line));put('claims',(state.seeds_and_claims||[]).map(line));put('mirrors',(state.metacognitive_mirrors||[]).map(mirrorLine));put('learning',(state.learning_and_stops||[]).map(line));put('events',(events.events||[]).map(line));await refreshChat()}catch(e){byId('health').textContent='监控暂不可用'}}byId('chatSend').addEventListener('click',sendChat);refresh();setInterval(refresh,1500);
</script></body></html>"""
